version: '3'

services:
  asterisk:
    image: andrewwyh/asterisk-docker:latest
    restart: always    
    volumes:
      - "${PWD}/etc/asterisk/:/etc/asterisk:rw"
      - "${PWD}/log/asterisk:/var/log/asterisk"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    network_mode: "host"
    logging:
      options:
              max-size: "1g"
